#!/usr/bin/env python3
"""
Batch geocodes all install addresses using Nominatim (OSM).
Nominatim ToS: max 1 req/sec, identify with a real User-Agent.
Output: installs.js  (window.INSTALL_DATA = [...])
Resume-safe: reads existing output and skips already-geocoded addresses.
"""

import csv, json, time, urllib.request, urllib.parse, os, sys, re

CSV_PATH  = "/Users/aryenwood/Downloads/All CPTL Install Addresses - Sheet1.csv"
OUT_PATH  = "/Users/aryenwood/claude-projects/capital-energy/installs.js"
DELAY     = 1.1   # seconds between requests (Nominatim limit = 1/s)
USER_AGENT = "CapitalEnergyPWA/1.0 (contact: aryen@capitalenergy.com)"

def load_existing():
    """Load already-geocoded addresses so we can skip them on resume."""
    if not os.path.exists(OUT_PATH):
        return {}
    try:
        with open(OUT_PATH) as f:
            txt = f.read()
        m = re.search(r'window\.INSTALL_DATA\s*=\s*(\[.*?\]);', txt, re.DOTALL)
        if not m:
            return {}
        data = json.loads(m.group(1))
        return {d['address']: d for d in data if 'lat' in d}
    except Exception as e:
        print(f"  [warn] Could not parse existing output: {e}")
        return {}

def geocode(address):
    """Returns (lat, lng) or None."""
    params = urllib.parse.urlencode({
        'q': address,
        'format': 'json',
        'limit': 1,
        'addressdetails': 0,
    })
    url = f"https://nominatim.openstreetmap.org/search?{params}"
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            results = json.loads(r.read())
        if results:
            return float(results[0]['lat']), float(results[0]['lon'])
    except Exception as e:
        print(f"  [error] {e}")
    return None

def strip_quotes(s):
    return s.strip().strip('"').strip("'").strip()

def write_output(records):
    js = "// Auto-generated by geocode_installs.py — do not edit manually\n"
    js += "window.INSTALL_DATA = " + json.dumps(records, indent=None, separators=(',', ':')) + ";\n"
    with open(OUT_PATH, 'w') as f:
        f.write(js)

def main():
    # Read all addresses from CSV
    with open(CSV_PATH, newline='', encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        addresses = [strip_quotes(row[0]) for row in reader if row and row[0].strip()]

    print(f"Total addresses: {len(addresses)}")

    # Load any existing geocoded data
    existing = load_existing()
    print(f"Already geocoded: {len(existing)}")

    records = list(existing.values())
    failed  = []
    todo    = [a for a in addresses if a not in existing]
    total   = len(todo)

    print(f"Remaining: {total}\n")

    for i, addr in enumerate(todo, 1):
        sys.stdout.write(f"\r[{i}/{total}] {addr[:60]:<60}")
        sys.stdout.flush()

        result = geocode(addr)
        if result:
            lat, lng = result
            records.append({'address': addr, 'lat': lat, 'lng': lng})
        else:
            failed.append(addr)
            records.append({'address': addr, 'lat': None, 'lng': None})

        # Write checkpoint every 50 records
        if i % 50 == 0:
            write_output([r for r in records if r['lat'] is not None])
            print(f"\n  [checkpoint] {i}/{total} done, {len(failed)} failed so far")

        time.sleep(DELAY)

    # Final write — only include successfully geocoded
    good = [r for r in records if r['lat'] is not None]
    write_output(good)

    print(f"\n\nDone.")
    print(f"  Geocoded successfully: {len(good)}")
    print(f"  Failed / not found:    {len(failed)}")
    if failed:
        print("\n  Failed addresses:")
        for a in failed[:20]:
            print(f"    {a}")
        if len(failed) > 20:
            print(f"    ... and {len(failed)-20} more")
    print(f"\nOutput written to: {OUT_PATH}")

if __name__ == '__main__':
    main()
